spring:
  datasource:
    url: jdbc:mysql://localhost:3306/currency_db
    username: root
    password: root
    platform: mysql
    initialize: false
  jpa:
    hibernate:
          ddl-auto: none
---
server:
  servlet:
    session:
      persistent: true
      timeout: -1s
      cookie:
        max-age: -1s
